### ISSUE TITLE
is there a way to present instead of push

### ISSUE THREAD

**Issue by emadhegab** [canopas/UIPilot#14]
I can't find a method that present / dismiss.  all i see is push / pop .. is there intention to add that?

**Comment by jimmy0251** [comment]
Currently there's no plan to add that as it's not part of the NavigationView. You can easily present popup in any screen inside UIPilot with
```
struct ContentView: View {
    
    @State var isPresent: Bool = false
    
    var body: some View {
            Button("Present detail") {
                self.isPresent = true
            }
            .sheet(isPresented: $isPresent, content: {PresentDetail()})
    }
}

struct PresentDetail: View {
    var body: some View {
        Text("This is detail")
            .padding()
    }
}
```

**Comment by jimmy0251** [comment]
Not sure how we can simplify this with UIPilot as the flow is already very simple.

**Comment by emadhegab** [comment]
true.. I just thought as you have .push method that you pass enum object to it.. would be great to be same for .present or .sheet , to have same behaviour for all routings

**Comment by jimmy0251** [comment]
IMO adding those functionality will add more complexity as there are not really part of the navigation stack, they are just presented on current screen.

It will also complicate flow like what happens if you push a route on top of presented one? Should it be added to previous pushed route or on top of presented route.
